services:
  - type: web
    name: egaki
    plan: free
    runtime: python
    buildCommand: pip install fastapi "uvicorn[standard]" websockets --break-system-packages
    startCommand: python server.py
